name: release-docs

on:
  push:
    branches: ["main", "docs/*"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Deploy docs
        run: |
          pip install -U pip poetry
          task docs:release
